=== CorunaDevelopers/community-tech/vigotech-schema.json
{
  "title": "VigoTech Alliance members JSON schema",
  "type": "object",
  "description": "",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "required": [
    "name",
    "logo"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "Alliance name"
    },
    "logo": {
      "type": "string",
      "description": "Logo url"
    },
    "sticker": {
      "type": "string",
      "description": "Sticker image url"
    },
    "links": {
      "type": "array",
      "description": "Alliance site and social links",
      "items": {
        "type": "object",
        "description": "Link",
        "required": [
          "key",
          "url"
        ],
        "properties": {
          "key": {
            "type": "string",
            "description": "Link key (used to show icon)"
          },
          "url": {
            "type": "string",
            "description": "Link url"
          }
        }
      }
    },
    "members": {
      "type": "array",
      "description": "Alliance members",
      "items": {
        "type": "object",
        "description": "Member",
        "required": [
          "key",
          "name",
          "logo"
        ],
        "properties": {
          "key": {
            "type": "string",
            "description": "Member unique id"
          },
          "name": {
            "type": "string",
            "description": "Alliance name"
          },
          "logo": {
            "type": "string",
            "description": "Logo url"
          },
          "sticker": {
            "type": "string",
            "description": "Sticker image url"
          },
          "links": {
            "type": "array",
            "description": "Alliance site and social links",
            "items": {
              "type": "object",
              "description": "Link",
              "required": [
                "key",
                "url"
              ],
              "properties": {
                "key": {
                  "type": "string",
                  "description": "Link key (used to show icon)"
                },
                "url": {
                  "type": "string",
                  "description": "Link url"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== CorunaDevelopers/community-tech/vigotech.json
{
  "name": "VigoTech Alliance",
  "logo": "https://github.com/VigoTech/Design-elements/blob/master/01%20IDENTIDAD%20CORPORATIVA/01%20EXPORT/PNG/Logo%20VIGOTECH_claim-es-horizontal-fondo-blanco.png?raw=true",
  "sticker": "http://hexb.in/hexagons/vigotech.png",
  "links": [
    {"key": "web", "url": "http://vigotech.org/"},
    {"key": "twitter", "url": "http://twitter.com/vigotechallianc"},
    {"key": "mail", "url": "alliance@vigotech.org"},
    {"key": "github", "url": "https://github.com/VigoTech"}
  ],
  "members": [
    {
      "key": "agilevigo",
      "name": "Agile Vigo",
      "logo": "http://vigotech.org/images/agile_vigo.jpg",
      "links": [
        {"key": "web", "url": "https://www.agilevigo.com/"},
        {"key":"twitter", "url": "https://twitter.com/agilevigo"},
        {"key":"meetup", "url": "https://www.meetup.com/es-ES/agile-vigo/"},
        {"key":"github", "url": "https://github.com/agileVigo"}
      ]
    },
    {
      "key": "aindustriosa",
      "name": "Aindustriosa",
      "logo": "http://vigotech.org/images/aindustriosa.png",
      "links": [
        {"key": "web", "url": "https://aindustriosa.org/"},
        {"key": "twitter", "url": "https://twitter.com/aindustriosa"},
        {"key": "meetup", "url": "https://www.meetup.com/es-ES/AIndustriosa/"},
        {"key": "youtube", "url": "https://www.youtube.com/channel/UC9DPKfcLiNd7SEU-QLlIG7A"}
      ]
    },
    {
      "key": "galpon",
      "name": "GALPon",
      "logo": "http://vigotech.org/images/galpon.png",
      "links": [
        {"key": "web", "url": "https://www.galpon.org"},
        {"key": "twitter", "url": "https://twitter.com/galpon"},
        {"key": "maillist", "url": "https://www.galpon.org/content/listas-correo-galpon"}
      ]
    },
    {
      "key": "galstech",
      "name": "GalsTech",
      "logo": "http://vigotech.org/images/galstech.png",
      "links": [
        {"key": "meetup", "url": "https://www.meetup.com/GalsTech/"},
        {"key": "twitter", "url": "https://twitter.com/galstech_?lang=es"}
      ]
    },
    {
      "key": "gdgvigo",
      "name": "GDG Vigo",
      "logo": "http://vigotech.org/images/gdg_vigo.png",
      "links": [
        {"key": "twitter", "url": "http://twitter.com/GDGVigo/"},
        {"key": "meetup", "url": "https://www.meetup.com/es-ES/GDGVigo/?chapter_analytics_code=UA-73757047-1"},
        {"key": "youtube", "url": "https://www.youtube.com/user/GDGVigo"}
      ]
    },
    {
      "key": "joomlavigo",
      "name": "Grupo de Usuarios de Joomla de Vigo",
      "logo": "http://vigotech.org/images/joomla_vigo.png",
      "links": [
        {"key": "web", "url": "https://www.joomlavigo.es/"},
        {"key": "twitter", "url": "https://twitter.com/JoomlaVigo"},
        {"key": "facebook", "url": "https://www.facebook.com/JoomlaVigo/"},
        {"key": "meetup", "url": "https://www.meetup.com/es-ES/Grupo-de-Usuarios-de-Joomla-de-Vigo/"}
      ]
    },
    {
      "key": "jsvigo",
      "name": "JavascriptVigo",
      "logo": "http://vigotech.org/images/jsvigo.png",
      "links": [
        {"key": "meetup", "url": "https://www.meetup.com/es-ES/JavaScriptVigo/"},
        {"key": "twitter", "url": "http://twitter.com/JavaScriptVigo/"},
        {"key": "youtube", "url": "https://www.youtube.com/channel/UCjFplxtEs0XtunTn-n0LUtQ"}
      ]
    },
    {
      "key": "phpvigo",
      "name": "PHPVigo",
      "logo": "http://vigotech.org/images/php_vigo.jpg",
      "links": [
        {"key": "web", "url": "http://phpvigo.com/"},
        {"key": "meetup", "url": "https://www.meetup.com/es-ES/PHPVigo/"},
        {"key": "twitter", "url": "https://twitter.com/phpvigo"},
        {"key": "github", "url": "https://github.com/phpvigo"},
        {"key": "youtube", "url": "https://www.youtube.com/c/phpvigo"}
      ]
    },
    {
      "key": "pythonvigo",
      "name": "PythonVigo",
      "logo": "http://vigotech.org/images/python_vigo.png",
      "links": [
        {"key": "web", "url": "https://www.python-vigo.es/"},
        {"key": "twitter", "url": "https://twitter.com/python_vigo?lang=es"},
        {"key": "maillist", "url": "https://lists.es.python.org/listinfo/vigo"},
        {"key": "youtube", "url": "https://www.youtube.com/channel/UCTUXabChakosnupWEnz4xTA"}
      ]
    },
    {
      "key": "seogalicia",
      "name": "Seo Galicia",
      "logo": "http://vigotech.org/images/seogalicia.png",
      "links": [
        {"key": "facebook", "url": "https://www.facebook.com/SEOGaliciaMeetup"},
        {"key": "meetup", "url": "https://www.meetup.com/es/SEO-Galicia/"},
        {"key": "twitter", "url": "https://twitter.com/seo_galicia"}
      ]
    },
    {
      "key": "sysadmingalicia",
      "name": "SysAdmin Galicia",
      "logo": "http://vigotech.org/images/sysadmin_galicia.jpg",
      "links": [
        {"key": "meetup", "url": "https://www.meetup.com/es-ES/Sysadmin-Galicia/"},
        {"key": "twitter", "url": "https://twitter.com/sysadmingalicia/"}
      ]
    },
    {
      "key": "uxgalicia",
      "name": "UX Galicia",
      "logo": "http://vigotech.org/images/ux_gal.jpg",
      "links": [
        {"key": "web", "url": "http://www.uxgalicia.com/"},
        {"key": "meetup", "url": "https://www.meetup.com/es-ES/Experiencia-de-Usuario-Meetup/"},
        {"key": "twitter", "url": "https://twitter.com/uxgalicia/"}
      ]
    },
    {
      "key": "vigobrain",
      "name": "Vigo Brain",
      "logo": "http://vigotech.org/images/vigobrain.png",
      "links": [
        {"key": "github", "url": "https://github.com/vigobrain/"},
        {"key": "meetup", "url": "https://www.meetup.com/es-ES/VigoBrain/"},
        {"key": "twitter", "url": "https://twitter.com/vigobrain/"}
      ]
    },
    {
      "key": "vigojug",
      "name": "VigoJUG",
      "logo": "http://vigotech.org/images/vigojug.jpg",
      "links": [
        {"key": "web", "url": "http://www.vigojug.org/" },
        {"key": "github", "url": "https://github.com/vigobrain/"},
        {"key": "meetup", "url": "https://www.meetup.com/es-ES/Vigo-JUG/"},
        {"key": "twitter", "url": "https://twitter.com/vigojug/"},
        {"key": "linkedin", "url": "https://www.linkedin.com/organization/11056204"},
        {"key": "youtube", "url": "https://www.youtube.com/channel/UCNOihTnorv6dZDANaPXgx_g"}
      ]
    }
  ]
}
